# Generated by Django 4.2.4 on 2023-09-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
