# Generated by Django 4.2.4 on 2023-10-01 19:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0003_alter_post_created_at_alter_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='title', editable=False, populate_from='title'),
        ),
    ]
