# Generated by Django 4.2.4 on 2023-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0004_practicequiz_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequiz',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
