# Generated by Django 4.2.4 on 2023-10-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0005_alter_post_slug_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='OnlineLearningSystem.question'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='OnlineLearningSystem.post'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'text')},
        ),
    ]
