# Generated by Django 4.2.4 on 2023-09-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0005_practicequiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicequiz',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
