# Generated by Django 4.2.4 on 2023-10-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0006_alter_choice_question_alter_reply_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='OnlineLearningSystem.practicequiz'),
        ),
    ]
