# Generated by Django 4.2.4 on 2023-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0007_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
