# Generated by Django 4.2.4 on 2023-09-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0007_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='chosen_choice',
            new_name='selected_choice',
        ),
    ]
