# Generated by Django 4.2.4 on 2023-10-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0008_quizresult_percentage_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='percentage_score',
        ),
    ]
