# Generated by Django 4.2.4 on 2023-11-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineLearningSystem', '0010_course_practicequiz_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_left', models.PositiveIntegerField(default=3)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineLearningSystem.practicequiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
