# Generated by Django 4.2.4 on 2023-11-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0011_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequiz',
            name='attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
