# Generated by Django 4.2.4 on 2023-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearningSystem', '0012_practicequiz_course_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
